== Groovy Fundamentals

=== Groovy Features

[.step]
* Simple Syntax (Less Noise)
* Operator Overloading
* Scripting Support
* Meta-Programming

=== Syntactic Sugar

[source,groovy,role='fragment']
.Maps and lists
----
Map map = [language: 'Groovy']
List list = ['foo', 'bar']
----

[source,groovy,role='fragment']
.Command chaining and optional parenthesis
----
// equivalent to: say(hello).to('Craig')
say hello to 'Craig' 
----

=== Operator Overloading

[role='operators',width=50]
|===

| a + b       | a.plus(b)

| a - b       | a.minus(b)

| a * b       | a.multiply(b)

| a ** b      | a.power(b)

| a / b       | a.div(b)

| a % b       | a.mod(b) 

| a \| b       | a.or(b)

| a & b       | a.and(b)

| a ^ b       | a.xor(b)

| a++ or ++a  | a.next()

| a-- or --a  | a.previous()

| a << b      | a.leftShift(b)

| a >> b      | a.rightShift(b)

| a <=> b     | a.compareTo(b)

|===

=== The MetaClass

* Every class in Groovy has a corresponding metaClass
* Class instances can also have custom metaClasses

=== Closures

A *first-class function* that can be:

* Passed as an argument
* Assigned to a variable
* Returned from a function

=== Closure Scope

this:: instance of the class the closure was defined
owner:: usually the same as this unless it was declared inside another closure
delegate:: same as owner but can be reassigned

=== Getters and Setters

[source,groovy,role='fragment']
----
class Person {
  String name
  String nickName
}
Person person = new Person()
----

[source,groovy,role='fragment']
.Equivilent to person.setName('Craig')
----
person.name = 'Craig' 
----

[source,groovy,role='fragment']
.Equivilent to println person.getName()
----
println person.name
----

[source,groovy,role='fragment']
.Equivilent to person.setNickName(person.getName())
----
person.nickName = person.name
----

=== Dynamic Properties

[source,groovy,role='fragment']
.Extending the Number class
----
Number.metaClass.getDollars = { delegate as BigDecimal }

Number.metaClass.getProperty = { String name ->
  def rates = [euros: 1.1f, pesos: 0.063f]
  delegate * (rates[name] as BigDecimal)
}
----

[source,groovy,role='fragment']
.Adding different currencies together
----
def total = 20.dollars + 40.euros + 200.pesos
assert total == 76.60
----

=== Dynamic Methods

[.source.groovy.fragment]
----
class Person {
  def methodMissing(String name, args) {
    if (name.startsWith('say')) {
      String message = (name - 'say').trim()
      println message
    }
  }
}
----

[.source.groovy.fragment]
.Trying out our dynamic method
----
Person you = new Person()
you.sayHello()
you."say Craig is Awesome"()
----


